title: Houda Khaled
description: Houda Khaled's personal site

url: http://houdak.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: Publications
   url: /pubs
 - title: Resources
   url: /resources

google_analytics: UA-131352185-1
